application: blockly-demo
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:
# Storage API.
- url: /storage
  script: storage.py
- url: /storage\.js
  static_files: storage.js
  upload: storage\.js

# Blockly files.
- url: /static
  static_dir: static
# Obsolete URL.
- url: /blockly
  static_dir: static

# Closure library for uncompiled Blockly.
- url: /closure-library-read-only
  static_dir: closure-library-read-only

# Redirect for root directory.
- url: /
  script: index_redirect.py
